Repository kubernetes/kubernetes-docs-zh, pull requests merged in 2018-10, with the labels that each got.

#574 cn-pr-trans-home-contribute-style-guide-20180710
  content/cn/docs/home/contribute/style-guide.md
Labels: cncf-cla: yes, size/XL

#573 Translate cn/docs/getting started guides/ubuntu/logging
  content/cn/docs/getting-started-guides/ubuntu/logging.md
Labels: cncf-cla: yes, lgtm, size/M

#572 translate cn/docs/getting started guides/ubuntu/local
  content/cn/docs/getting-started-guides/ubuntu/local.md
Labels: cncf-cla: yes, lgtm, size/L

#576 update reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS
