Repository kubernetes/kubernetes-docs-zh, pull requests merged in 2018-04, with the labels that each got.

#340 kubeadm-alpha-phase-bootstrap-token-a-pr-2018-3-30
  docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_bootstrap-token_all.md
Labels: cncf-cla: yes, size/M

#324 Translate “index.md“
  docs/imported/index-2018-02-04.md
  docs/imported/index.md
Labels: cncf-cla: yes, size/S

#338 tasks-administer-cluster-dns-debugging-resolution-2018-3-19
  docs/tasks/administer-cluster/dns-debugging-resolution.md
Labels: cncf-cla: yes, size/L

#335 reference-api-concepts-pr-2018-2-4
  docs/reference/api-concepts.md
Labels: cncf-cla: yes, size/L

#329 Translate "mentoring.md"
  docs/imported/community/mentoring-2018-02-04.md
  docs/imported/community/mentoring-2018-03-19.md
  docs/imported/community/mentoring.md
Labels: cncf-cla: yes, size/L

#321 Update extending.md
  docs/concepts/overview/extending.md
  docs/getting-started-guides/fedora/fedora_ansible_config.md
  docs/tasks/access-application-cluster/access-cluster.md
Labels: cncf-cla: yes, size/S

#325 Translate “devel.md“
  docs/imported/community/devel-2018-02-04.md
  docs/imported/community/devel-2018-03-19.md
  docs/imported/community/devel.md
Labels: cncf-cla: yes, size/L

#327 fix:"kubernetes"should be "Kubernetes"
  docs/admin/kubelet.md
Labels: cncf-cla: yes, size/XS

#332 getting-started-guides-ubuntu-rancher-2018-03-19
  docs/getting-started-guides/ubuntu/rancher.md
Labels: cncf-cla: yes, size/L

#348 fix typo in charts title
  chart.html
Labels: cncf-cla: yes, size/XS

#346 Generated kubeadm alpha phase controlplane controller manager-2018-03-31
  docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_controlplane_controller-manager.md
Labels: cncf-cla: yes, size/S

#345 reference-setup-tools-kubeadm-generated-kubeadmin_alpha_phase_addon_all-2018-03-31
  docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_addon_all.md
Labels: cncf-cla: yes, size/M

#343 kubeadm-alpha-phase-bootstrap-token-pr-2018-3-30
  docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_bootstrap-token.md
Labels: cncf-cla: yes, size/S

#342 kubeadm-upgrade-pr-2018-3-30
  docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade.md
Labels: cncf-cla: yes, size/M

#339 reference-setup-tools-kubeadm-implementation-details-2018-03-19
  docs/reference/setup-tools/kubeadm/implementation-details-2018-02-04.md
  docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: cncf-cla: yes, size/XXL

#336 reference-design-docs-overview-pr-2018-2-4
  docs/reference/design-docs/overview.md
Labels: cncf-cla: yes, size/S

#333 home-contribute-localization-pr-2018-3-19
  docs/home/contribute/localization.md
Labels: cncf-cla: yes, size/L

#331 tasks-inject-data-application-environment-variable-expose-pod-informa…
  docs/tasks/inject-data-application/environment-variable-expose-pod-information-2017-9-15.md
  docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
Labels: cncf-cla: yes, size/L

#323 tasks-administer-cluster-encrypt-data-pr-2018-03-19
  docs/tasks/administer-cluster/encrypt-data.md
Labels: cncf-cla: yes, size/L

#352 fix:"kubernetes" should be "Kubernetes"
  docs/tools/index.md
Labels: cncf-cla: yes, lgtm, size/XS

#334 home-contribute-practicepating-pr-2018-3-19
  docs/home/contribute/participating.md
Labels: cncf-cla: yes, lgtm, size/L

#372 fix:“签准" should be "前缀"
  docs/getting-started-guides/gce.md
Labels: cncf-cla: yes, size/XS

#359 add missing `
  docs/concepts/configuration/manage-compute-resources-container.md
Labels: cncf-cla: yes, lgtm, size/XS

#357 fix `s chema` to `schema`
  docs/concepts/workloads/controllers/deployment.md
Labels: cncf-cla: yes, size/XS

#371 fix:"他"should be "它"
  docs/getting-started-guides/dcos.md
Labels: cncf-cla: yes, size/XS

#370 fix:"aaS" should be "IaaS "
  docs/getting-started-guides/cloudstack.md
Labels: cncf-cla: yes, size/XS

#355 Translated federation-api.md
  docs/home/contribute/generated-reference/federation-api-2018-02-04.md
  docs/home/contribute/generated-reference/federation-api-2018-03-19.md
  docs/home/contribute/generated-reference/federation-api.md
  docs/home/contribute/generated-reference/kubernetes-api.md
Labels: cncf-cla: yes, size/L

#369 fix:从标题中删除句号
  docs/getting-started-guides/clc.md
Labels: cncf-cla: yes, size/XS

#368 fix "投建"应为“构建”
  docs/getting-started-guides/windows/index.md
Labels: cncf-cla: yes, size/XS

#367 fix: add "，"
  docs/getting-started-guides/ubuntu/backups.md
Labels: cncf-cla: yes, size/XS

#366 fix:"per-node or per-pod"的译文
  docs/getting-started-guides/rkt/index.md
Labels: cncf-cla: yes, size/XS

#365 fix:键值
  docs/getting-started-guides/mesos/index.md
Labels: cncf-cla: yes, size/XS

#364 fix:" coreOS" should be "CoreOS"
  docs/getting-started-guides/coreos/index.md
Labels: cncf-cla: yes, size/XS

#363 fix:"docker" should be "Docker"
  docs/concepts/containers/images.md
Labels: cncf-cla: yes, size/XS

#362 Update kubectl-overview.md
  docs/user-guide/kubectl-overview.md
Labels: cncf-cla: yes, size/XS

#360 indentation
  docs/concepts/configuration/taint-and-toleration.md
Labels: cncf-cla: yes, size/XS

#358 delete redundant _
  docs/concepts/workloads/controllers/statefulset.md
Labels: cncf-cla: yes, size/XS

#356 concepts-overview-object-management-kubectl-imperative-config-pr-2018-02-04
  docs/concepts/overview/object-management-kubectl/imperative-config.md
Labels: cncf-cla: yes, size/L

#354 Translate keps
  docs/imported/community/keps-2018-02-04.md
  docs/imported/community/keps-2018-03-19.md
  docs/imported/community/keps.md
Labels: cncf-cla: yes, size/XXL

#353 fix: still have"kubernetes" should be "Kubernetes"
  docs/tools/index.md
Labels: cncf-cla: yes, size/XS

#350 fix:line156 "anti-affinity" should be"Anti-affinity"
  docs/concepts/configuration/assign-pod-node.md
Labels: cncf-cla: yes, size/XS

#349 fix typo
  docs/setup/pick-right-solution.md
Labels: cncf-cla: yes, size/XS

#375 Update _viewing-a-pod.md
  docs/tasks/administer-cluster/apply-resource-quota-limit.md
  docs/tasks/administer-cluster/calico-network-policy.md
  docs/user-guide/pods/_viewing-a-pod.md
Labels: cncf-cla: yes, size/M

#374 fix:“竞价与永久” should be “按需”
  docs/getting-started-guides/kops.md
Labels: cncf-cla: yes, size/XS

#373 fix:"组建"should be "组件"
  docs/getting-started-guides/gce.md
Labels: cncf-cla: yes, size/XS

#379 fix:"pod"should be "Pod"
  docs/getting-started-guides/windows/index.md
Labels: cncf-cla: yes, size/XS

#384 fix:"deployment"should be "Deployment"
  docs/reference/workloads.md
Labels: cncf-cla: yes, size/XS

#381 fix:“级” should be "及"
  docs/imported/community/keps.md
Labels: cncf-cla: yes, size/XS

#380 fix:delete dulplicate line
  docs/getting-started-guides/clc.md
Labels: cncf-cla: yes, size/XS

#385 fix:"群集"should be "集群"
  docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: cncf-cla: yes, size/XS

#397 fix:"试例"should be "示例"
  docs/getting-started-guides/gce.md
Labels: cncf-cla: yes, size/XS

#398 fix:“害”should be "还"
  docs/getting-started-guides/kops.md
Labels: cncf-cla: yes, size/XS

#392 fix:"正真" should be "真正"
  docs/user-journeys/users/application-developer/intermediate.md
Labels: cncf-cla: yes, size/XS

#388 fix:"Pods" should be "Pod"
  docs/tasks/index.md
Labels: cncf-cla: yes, size/XS

#394 fix:"包“should be "括"
  docs/user-guide/jsonpath.md
Labels: cncf-cla: yes, size/XS

#407 fix:delete "的"
  docs/user-guide/walkthrough/k8s201.md
Labels: cncf-cla: yes, size/XS

#406 fix :typo "CUP" should be "CPU"
  docs/user-guide/kubectl/index.md
Labels: cncf-cla: yes, size/XS

#405 fix:typo:"kubeernetes"should be "kubernetes"
  docs/getting-started-guides/kops.md
Labels: cncf-cla: yes, size/XS

#402 fix blod text
  docs/concepts/index.md
Labels: cncf-cla: yes, size/XS

#401 fix :"kubernetes" should be "Kubernetes"
  docs/user-guide/docker-cli-to-kubectl.md
Labels: cncf-cla: yes, size/XS

#400 fix:"kompose" should be "Kompose"
  docs/tools/index.md
Labels: cncf-cla: yes, size/XS

#396 fix:add space
  docs/user-guide/kubectl-conventions.md
Labels: cncf-cla: yes, size/XS

#399 fix:add translation
  docs/tools/kompose/user-guide.md
Labels: cncf-cla: yes, size/XS

#391 Delete ,
  docs/tasks/configure-pod-container/configure-projected-volume-storage.md
Labels: cncf-cla: yes, size/XS

#382 fix:delete "支持“
  docs/reference/api-concepts.md
Labels: cncf-cla: yes, size/XS

#393 tasks-debug-application-cluster-debug-cluster-pr-2018-03-19
  docs/tasks/debug-application-cluster/debug-cluster.md
Labels: cncf-cla: yes, size/L

#408 fix "群集"should be "集群"
  docs/tutorials/object-management-kubectl/object-management.md
Labels: cncf-cla: yes, size/XS

#387 fix:delete ";"
  docs/setup/independent/high-availability.md
Labels: cncf-cla: yes, size/XS

#389 fix:"services" should be "service"
  docs/tasks/access-application-cluster/access-cluster.md
Labels: cncf-cla: yes, size/XS

#395 fix:"kubernetes"should be "Kubernetes"
  docs/user-guide/kubectl-cheatsheet.md
Labels: cncf-cla: yes, size/XS

#377 concepts-overview-object-management-kubectl-imperative-command-pr-2018-02-04
  docs/concepts/overview/object-management-kubectl/imperative-command.md
Labels: cncf-cla: yes, size/L

#411 Typo fix: Fibre Channl->Fibre Channel
  docs/concepts/storage/persistent-volumes.md
Labels: cncf-cla: yes, size/XS

#412 Typo fix in custom-resources.md
  docs/concepts/api-extension/custom-resources.md
Labels: cncf-cla: yes, size/XS

#418 Typo fix in nodes.md
  docs/concepts/architecture/nodes.md
Labels: cncf-cla: yes, size/XS

#420 Typo fix: hide the english description
  docs/tasks/debug-application-cluster/debug-init-containers.md
Labels: cncf-cla: yes, size/XS

#424 Typo fix： 应用城西-》应用程序
  docs/concepts/workloads/controllers/daemonset.md
Labels: cncf-cla: yes, size/XS

#425 Typo fix：工作人员-》工作节点 等三处修改
  docs/getting-started-guides/ubuntu/rancher.md
Labels: cncf-cla: yes, size/XS

#435 Typo fix :KUbernetes->Kubernetes
  docs/concepts/overview/working-with-objects/kubernetes-objects.md
Labels: cncf-cla: yes, size/XS

#434 fix :"落在的" should be "所在的"
  docs/concepts/configuration/assign-pod-node.md
Labels: cncf-cla: yes, size/XS

#433 fix:typo "Ddocker" should be "Docker"
  docs/tutorials/stateless-application/hello-minikube.md
Labels: cncf-cla: yes, size/XS

#432 fix:"如果您觉得您的技术比较牛"的翻译
  docs/tutorials/stateless-application/guestbook.md
Labels: cncf-cla: yes, size/XS

#431 fix:"CPUs" should be "CPU"
  docs/tutorials/stateful-application/zookeeper.md
Labels: cncf-cla: yes, size/XS

#430 fix:delete space
  docs/tutorials/stateful-application/cassandra.md
Labels: cncf-cla: yes, size/XS

#429 fix:add "s"
  docs/tutorials/stateful-application/basic-stateful-set.md
Labels: cncf-cla: yes, size/XS

#428 fix: "Services" should be "Service"
  docs/tutorials/services/source-ip.md
Labels: cncf-cla: yes, size/XS

#427 Typo fix Secretes->Secrets
  docs/tasks/configure-pod-container/configure-projected-volume-storage.md
Labels: cncf-cla: yes, size/XS

#426 Typo fix: deplyment->deployment
  docs/tools/kompose/user-guide.md
Labels: cncf-cla: yes, size/XS

#423 Typo fix 标点符号中文化
  docs/concepts/workloads/controllers/replicaset.md
Labels: cncf-cla: yes, size/M

#422 Typo fix: 语句表达不符合中文习惯
  docs/tasks/administer-cluster/cpu-default-namespace.md
Labels: cncf-cla: yes, size/XS

#421 Typo fix request的翻译：申请-》请求
  docs/tasks/configure-pod-container/quality-service-pod.md
Labels: cncf-cla: yes, size/XS

#419 Typo fix in update-api-object-kubectl-patch.md
  docs/tasks/run-application/update-api-object-kubectl-patch.md
Labels: cncf-cla: yes, size/XS

#417 翻译完成 " docs/imported/community/guide"
  docs/imported/community/guide-2018-02-04.md
  docs/imported/community/guide-2018-03-19.md
  docs/imported/community/guide.md
Labels: cncf-cla: yes, size/XL

#415 fix:delete ","
  docs/tools/index.md
Labels: cncf-cla: yes, size/XS

#414 Typo fix in admission-controllers.md
  docs/admin/admission-controllers.md
Labels: cncf-cla: yes, size/XS

#413 Typo fix in openstack-heat.md
  docs/getting-started-guides/openstack-heat.md
Labels: cncf-cla: yes, size/XS

#410 Typo fix in ubuntu/operational-considerations.md
  docs/getting-started-guides/ubuntu/operational-considerations.md
Labels: cncf-cla: yes, size/XS

#409 fix "又是"should be "有时"
  docs/getting-started-guides/kops.md
Labels: cncf-cla: yes, size/XS

#403 delete english description
  docs/concepts/cluster-administration/logging.md
Labels: cncf-cla: yes, size/XS

#386 Translated kubectl.md
  docs/home/contribute/generated-reference/kubectl-2018-02-04.md
  docs/home/contribute/generated-reference/kubectl-2018-03-19.md
  docs/home/contribute/generated-reference/kubectl.md
Labels: cncf-cla: yes, size/XL

#441 Typo fix: 荚列表-》pod列表
  docs/user-guide/kubectl-overview.md
Labels: cncf-cla: yes, size/XS

#442 Kubernetes和Kubelet两个专有名词统一大小写
  docs/user-guide/walkthrough/k8s201.md
Labels: cncf-cla: yes, size/XS

#438 fix:"裸金属上"should be"裸机"
  docs/admin/high-availability/building.md
Labels: cncf-cla: yes, size/XS

#440 Typo fix: 进行认证是-》进行认证时；饱含-》包含
  docs/admin/authentication.md
Labels: cncf-cla: yes, size/XS

#439 文中把中文翻译给隐藏了，相反却把英文原文没有隐藏
  docs/user-guide/kubectl-cheatsheet.md
Labels: cncf-cla: yes, size/S

#436 fix: “strange”译为"异常"，更为通顺
  docs/getting-started-guides/ubuntu/backups.md
Labels: cncf-cla: yes, size/XS

#445 fix :add "。"
  docs/tasks/example-task-template.md
Labels: cncf-cla: yes, size/XS

#449 typo fix: 不同的时-》不同的是
  docs/admin/accessing-the-api.md
Labels: cncf-cla: yes, size/XS

#446 翻译错误：用户账号准入控制器（Service account admission controller）
  docs/admin/service-accounts-admin.md
Labels: cncf-cla: yes, size/XS

#451 命令行的字体背景加深错位了
  docs/admin/kubeadm.md
Labels: cncf-cla: yes, size/XS

#450 fix :"淆" change to "杂"
  docs/tasks/access-application-cluster/access-cluster.md
Labels: cncf-cla: yes, size/XS

#448 Typo fix：发型的证书-》发行的证书
  docs/admin/kubelet-tls-bootstrapping.md
Labels: cncf-cla: yes, size/XS

#447 publicAddressOverride参数的解释翻译不准确
  docs/admin/salt.md
Labels: cncf-cla: yes, size/XS

#444 fix:delete,add 或
  docs/tasks/index.md
Labels: cncf-cla: yes, size/XS

#443 Typo fix：应用的多个示例在相同的机器上共存-》应用的多个实例在相同的机器上共存
  docs/tutorials/stateful-application/zookeeper.md
Labels: cncf-cla: yes, size/XS

#437 fix:改变“的”的位置
  docs/getting-started-guides/clc.md
Labels: cncf-cla: yes, size/XS

#347 setup-tools-kubeadm-generaed_kubeadm_join_2018-03-31
  docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
Labels: cncf-cla: yes, size/M
