Repository kubernetes/kubernetes-docs-zh, pull requests merged in 2018-03, with the labels that each got.

#263 Typo fix "新的 deployment"->"新的 Deployment"
  docs/concepts/workloads/controllers/deployment.md
Labels: cncf-cla: yes, size/XS

#261 user-journeys-users-cluster-operator-intermediate-pr-2018-02-04
  docs/user-journeys/users/cluster-operator/intermediate.md
Labels: cncf-cla: yes, size/L

#260 configMap 使用说明
  docs/user-guide/configmap/README.md
Labels: cncf-cla: yes, size/M

#265 Typo fix "建立权限许可."->"建立权限许可。"
  docs/concepts/cluster-administration/cluster-administration-overview.md
Labels: cncf-cla: yes, size/XS

#268 Typo delete duplicated "]"
  docs/concepts/overview/extending.md
Labels: cncf-cla: yes, size/XS

#267 Typo fix delete duplicated "'", Typo fix "Portwork"->"Portworx"
  docs/concepts/storage/volumes.md
Labels: cncf-cla: yes, size/XS

#266 Typo add ";"
  docs/concepts/containers/images.md
Labels: cncf-cla: yes, size/XS

#204 getting-started-guides-aws-pr-2017-10-15
  docs/getting-started-guides/aws.md
Labels: cncf-cla: yes, size/L

#262 user-journeys-users-application-developer-intermeidate-pr-2018-02-04
  docs/user-journeys/users/application-developer/intermediate.md
Labels: cncf-cla: yes, size/L

#257 tutorials-online-training-overview-pr-2018-02-04
  docs/tutorials/online-training/overview.md
Labels: cncf-cla: yes, size/S

#276 Typo delete duplicated "。。"
  docs/user-journeys/users/cluster-operator/foundational.md
Labels: cncf-cla: yes, lgtm, size/XS

#275 Typo fix "纪录日志"-》“记录日志”
  docs/user-journeys/users/cluster-operator/intermediate.md
Labels: cncf-cla: yes, size/XS

#278 fix misspelling of Kubernetes
  docs/concepts/workloads/controllers/deployment.md
  docs/concepts/workloads/controllers/statefulset-2017-7-15.md
  docs/concepts/workloads/controllers/statefulset.md
  docs/home/contribute/includes-2017-12-03.md
Labels: cncf-cla: yes, size/L

#277 Typo fix "Replication Controller"->"ReplicationController"
  docs/user-guide/kubectl/index.md
Labels: cncf-cla: yes, size/XS

#274 admin-high-availability-building-pr-2018-02-04
  docs/admin/high-availability/building.md
  docs/admin/high-availability/index.md
Labels: cncf-cla: yes, size/XL

#273 setup-hosted-solutions-overview-pr-2018-02-04
  docs/setup/hosted-solutions/overview.md
Labels: cncf-cla: yes, size/XS

#272 kubernetes-components-pr
  docs/home/contribute/generated-reference/kubernetes-components.md
Labels: cncf-cla: yes, size/L

#271 getting-started-guides-ubuntu-security-pr
  docs/getting-started-guides/ubuntu/security.md
Labels: cncf-cla: yes, size/M

#270 getting-started-guides-ubuntu-troubleshooting-pr
  docs/getting-started-guides/ubuntu/troubleshooting.md
Labels: cncf-cla: yes, size/L

#269 setup-independent-high-availability-pr-2018-02-04
  docs/setup/independent/high-availability.md
Labels: cncf-cla: yes, size/L

#280 concepts-configuration-assign-pod-node-update-20180312
  docs/concepts/configuration/assign-pod-node.md
Labels: cncf-cla: yes, size/XS

#282 Fix descriptions in configure-access-multiple-clusters.md
  docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Labels: cncf-cla: yes, lgtm, size/XS

#283 Fix description in connecting-frontend-backend.md
  docs/tasks/access-application-cluster/connecting-frontend-backend.md
Labels: cncf-cla: yes, lgtm, size/XS

#284 Typo fix a clerical error in list-all-running-container-images.md
  docs/tasks/access-application-cluster/list-all-running-container-images.md
Labels: cncf-cla: yes, size/XS

#285 Update create-external-load-balancer.md
  docs/tasks/access-application-cluster/create-external-load-balancer.md
Labels: cncf-cla: yes, lgtm, size/XS

#292 Update README-CN.md
  README-CN.md
Labels: cncf-cla: yes, size/XS

#290 Update romana-network-policy.md
  docs/tasks/administer-cluster/romana-network-policy.md
Labels: cncf-cla: yes, lgtm, size/XS

#286 fix 2 typo errors in web-ui-dashboard.md
  docs/tasks/access-application-cluster/web-ui-dashboard.md
Labels: cncf-cla: yes, size/XS

#294 fix typo
  docs/concepts/architecture/master-node-communication.md
Labels: cncf-cla: yes, lgtm, size/XS

#295 Typo fix in kubeadm.md
  docs/reference/setup-tools/kubeadm/kubeadm.md
Labels: cncf-cla: yes, size/XS

#289 Update calico-network-policy.md
  docs/tasks/administer-cluster/calico-network-policy.md
Labels: cncf-cla: yes, size/XS

#288 Update access-cluster-api.md
  docs/tasks/administer-cluster/access-cluster-api.md
Labels: cncf-cla: yes, size/XS

#279 tasks-administer-cluster-configure-upgrade-etcd-pr-2018-02-04
  docs/tasks/administer-cluster/configure-upgrade-etcd-2017-8-15.md
  docs/tasks/administer-cluster/configure-upgrade-etcd.md
Labels: cncf-cla: yes, lgtm, size/XL

#315 kubeadm-alpha-phase-certs-all-pr-2018-3-21
  docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_all.md
Labels: cncf-cla: yes, size/M

#314 README-pr-2018-3-21
  docs/reference/setup-tools/kubeadm/generated/README.md
Labels: cncf-cla: yes, size/XS

#313 fix : "pod" should be "Pod"
  docs/concepts/architecture/cloud-controller.md
Labels: cncf-cla: yes, size/XS

#311 Update pod-overview.md
  docs/concepts/workloads/pods/pod-overview.md
Labels: cncf-cla: yes, size/S

#310 Update resource-quotas.md
  docs/concepts/policy/resource-quotas.md
Labels: cncf-cla: yes, size/S

#309 Update apiserver-aggregation.md
  docs/concepts/api-extension/apiserver-aggregation.md
Labels: cncf-cla: yes, size/XS

#306 home-supported-doc-versions-pr-2018-02-04
  docs/home/supported-doc-versions.md
Labels: cncf-cla: yes, size/S

#305 reference-kubectl-cheatsheet-pr-2018-03-19
  docs/reference/kubectl/cheatsheet-2017-12-03.md
  docs/reference/kubectl/cheatsheet-2018-02-04.md
  docs/reference/kubectl/cheatsheet.md
Labels: cncf-cla: yes, size/XL

#302 Typo fix in configure-access-multiple-clusters.md
  docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Labels: cncf-cla: yes, size/S

#301 Typo fix sercret->secret
  docs/tasks/tls/managing-tls-in-a-cluster.md
Labels: cncf-cla: yes, size/XS

#297 fix some typos.
  docs/tasks/debug-application-cluster/logging-stackdriver.md
Labels: cncf-cla: yes, size/S

#291 debug-application-cluster-debug-application-introspection-pr-2018-02-04
  docs/tasks/debug-application-cluster/debug-application-introspection.md
Labels: cncf-cla: yes, size/M

#281 tasks-debug-application-cluster-audit-pr-2018-02-04
  docs/tasks/debug-application-cluster/audit.md
Labels: cncf-cla: yes, size/L

#223 kubeadm_alpha_phase_bootstrap-token_node_pr_2018_1_30
  docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_bootstrap-token_node.md
Labels: cncf-cla: yes, size/S

#317 fix：yaml文件格式，不需要双引号
  docs/concepts/configuration/assign-pod-node.md
Labels: cncf-cla: yes, size/XS

#328 fix:typo "pod" should be "Pod"
  docs/concepts/architecture/cloud-controller.md
Labels: cncf-cla: yes, size/XS

#330 tasks-debug-application-cluster-debug-application-pr-2018-03-19
  docs/tasks/debug-application-cluster/debug-application.md
Labels: cncf-cla: yes, size/L

#322 Update guestbook.md
  docs/tutorials/stateless-application/guestbook.md
Labels: cncf-cla: yes, size/S
