Repository kubernetes/kubernetes-docs-zh, pull requests merged in 2018-09, with the labels that each got.

#515 cilium-network-policy-pr-2018-8-23
  content/cn/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
Labels: cncf-cla: yes, lgtm, size/L

#519 Translate concepts_configuration_taint-and-toleration
  content/cn/docs/concepts/configuration/taint-and-toleration.md
Labels: cncf-cla: yes, lgtm, size/L

#542 translate translate-compose-kubernetes.md
  docs/tasks/configure-pod-container/translate-compose-kubernetes.md
Labels: cncf-cla: yes, size/XL

#544 commit kubeadm-upgrade-1-9
  content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-9.md
Labels: cncf-cla: yes, size/L

#518 translate encrypt-data.md
  content/cn/docs/tasks/administer-cluster/encrypt-data.md
Labels: cncf-cla: yes, lgtm, size/L

#530 translate blog 2016-04-00-Kubernetes-Network-Policy-APIs
  content/cn/blog/_posts/2016-04-00-Kubernetes-Network-Policy-APIs.md
Labels: cncf-cla: yes, size/L

#545 trans blog 2018-03-00-Principles-Of-Container-App-Design
  content/cn/blog/_posts/2018-03-00-Principles-Of-Container-App-Design.md
Labels: cncf-cla: yes, lgtm, size/M

#546 Translate kubectl.md
  content/cn/docs/reference/kubectl/kubectl.md
Labels: cncf-cla: yes, size/L

#547 translate access-cluster.md
  content/cn/docs/tasks/access-application-cluster/access-cluster.md
Labels: cncf-cla: yes, size/XL

#548 translate configure-dns-cluster.md
  content/cn/docs/tasks/access-application-cluster/configure-dns-cluster.md
Labels: cncf-cla: yes, size/S

#549 translate create-external-load-balancer.md
  content/cn/docs/tasks/access-application-cluster/create-external-load-balancer.md
Labels: cncf-cla: yes, size/L

#540 translate kube-scheduler.md
  content/cn/docs/reference/command-line-tools-reference/kube-scheduler.md
Labels: cncf-cla: yes, lgtm, size/L

#534 Congfairy patch 2
  content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
Labels: cncf-cla: yes, size/XL

#531 cn-pr-trans-referece-access-authn-authz-authorization-20180710
  content/cn/docs/reference/access-authn-authz/authorization.md
Labels: cncf-cla: yes, size/L

#529 translate security.md
  content/cn/docs/getting-started-guides/ubuntu/security.md
Labels: cncf-cla: yes, size/M

#528 translate audit.md
  content/cn/docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#550 delete extra useless characters in README-cn
  README-CN.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#566 translate setup-extension-api-server.md
  content/cn/docs/tasks/access-kubernetes-api/setup-extension-api-server.md
Labels: cncf-cla: yes, size/L

#565 translate assign-pods-nodes.md
  content/cn/docs/tasks/configure-pod-container/assign-pods-nodes.md
Labels: cncf-cla: yes, size/L

#517 translate kubelet.md
  content/cn/docs/reference/command-line-tools-reference/kubelet.md
Labels: cncf-cla: yes, size/L

#533 2018-07-09-IPVS-In-Cluster-Load-Balancing-pr-2018-08-28
  content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
Labels: cncf-cla: yes, lgtm, size/L

#551 tools.md tranlate
  content/cn/docs/reference/tools.md
Labels: cncf-cla: yes, lgtm, size/L

#553 translate list-all-running-container-images.md
  content/cn/docs/tasks/access-application-cluster/list-all-running-container-images.md
Labels: cncf-cla: yes, size/L

#554 translate kube-proxy.md
  content/cn/docs/reference/command-line-tools-reference/kube-proxy.md
Labels: cncf-cla: yes, size/L

#555 translate load-balance-access-application-cluster.md
  content/cn/docs/tasks/access-application-cluster/load-balance-access-application-cluster.md
Labels: cncf-cla: yes, size/L

#556 translate port-forward-access-application-cluster.md
  content/cn/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
Labels: cncf-cla: yes, size/L

#557 translate service-access-application-cluster.md
  content/cn/docs/tasks/access-application-cluster/service-access-application-cluster.md
Labels: cncf-cla: yes, size/L

#558 translate docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
Labels: cncf-cla: yes, size/L

#563 translate content/en/docs/tasks/tools/install-kubeadm.md
  content/cn/docs/tasks/tools/install-kubeadm.md
Labels: cncf-cla: yes, lgtm, size/L

#571 Translate docs/getting-started-guides/ubuntu/backups.md
  content/cn/docs/getting-started-guides/ubuntu/backups.md
Labels: cncf-cla: yes, lgtm, size/L

#570 Translate `docs/getting-started-guides/ubuntu/installation.md`
  content/cn/docs/getting-started-guides/ubuntu/installation.md
Labels: cncf-cla: yes, lgtm, size/XL

#569 cn-pr-trans-referece-access-authn-authz-authentication-20180710
  content/cn/docs/reference/access-authn-authz/authentication.md
Labels: cncf-cla: yes, lgtm, size/XXL

#567 translate configure-aggregation-layer.md
  content/cn/docs/tasks/access-kubernetes-api/configure-aggregation-layer.md
Labels: cncf-cla: yes, lgtm, size/M

#564 translate Resource-Usage-Monitoring-Kubernetes.md
  content/cn/blog/_posts/2015-05-00-Resource-Usage-Monitoring-Kubernetes.md
Labels: cncf-cla: yes, lgtm, size/L
