Repository kubernetes/kubernetes-docs-zh, pull requests merged in 2018-02, with the labels that each got.

#213 concepts-example-concept-template-pr
  docs/concepts/example-concept-template.md
Labels: cncf-cla: yes, size/M

#250 user-journeys-users-application-developer-advanced-pr-20180210
  docs/user-journeys/users/application-developer/advanced.md
Labels: cncf-cla: yes, size/L

#249 getting-started-guides-ubuntu-local-pr
  docs/getting-started-guides/ubuntu/local.md
Labels: cncf-cla: yes, size/M

#247 getting-started-guides-stackpoint-pr
  docs/getting-started-guides/stackpoint.md
Labels: cncf-cla: yes, size/L

#245 getting-started-guided-fedora-fedora_ansible_config-pr
  docs/getting-started-guides/fedora/fedora_ansible_config.md
Labels: cncf-cla: yes, size/L

#244 concepts-overview-object-management-kubectl-overview-pr-2018-02-04
  docs/concepts/overview/object-management-kubectl/overview.md
Labels: cncf-cla: yes, size/L

#243 setup-building-from-source-pr-2018-02-04
  docs/setup/building-from-source.md
Labels: cncf-cla: yes, size/S

#242 reference-feature-gates-pr-2018-02-04
  docs/reference/feature-gates.md
Labels: cncf-cla: yes, size/L

#252 getting-started-guides-ubuntu-operational-considerations-pr
  docs/getting-started-guides/ubuntu/operational-considerations.md
Labels: cncf-cla: yes, size/M

#255 modify some translations
  docs/concepts/cluster-administration/federation.md
Labels: cncf-cla: yes, size/S

#254 getting-started-guides-ubuntu-scaling-pr
  docs/getting-started-guides/ubuntu/scaling.md
Labels: cncf-cla: yes, size/M

#253 task-user-journeys-users-cluster-operator-foundational-2018-2-21
  docs/user-journeys/users/cluster-operator/foundational.md
Labels: cncf-cla: yes, size/L

#256 Fix reference to Python client library
  docs/concepts/overview/working-with-objects/kubernetes-objects.md
  docs/reference/client-libraries.md
  docs/reference/index.md
  docs/tasks/access-application-cluster/access-cluster.md
  docs/tasks/administer-cluster/access-cluster-api.md
Labels: cncf-cla: yes, size/M
