Repository kubernetes/kubernetes-docs-zh, pull requests merged in 2018-08, with the labels that each got.

#497 Update SIG Azure reviewers (take 2)
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, sig/azure, size/XS

#503 Empty OWNERS_ALIASES except SIG Azure by request
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/L

#504 增加翻译贡献指引文档
  README-CN.md
  README.md
Labels: cncf-cla: yes, size/L

#511 calico-network-policy-pr-2018-8-22
  content/cn/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md
Labels: cncf-cla: yes, size/M

#507 cn-pr-blog-2016-04-00-Kubernetes-On-Aws_15
  content/cn/blog/_posts/2016-04-00-Kubernetes-On-Aws_15.md
Labels: cncf-cla: yes, size/L

#508 Translate sysctl-cluster.md
  content/cn/docs/tasks/administer-cluster/sysctl-cluster.md
Labels: cncf-cla: yes, size/L

#510 romana-network-policy-pr-2018-8-22
  content/cn/docs/tasks/administer-cluster/network-policy-provider/romana-network-policy.md
Labels: cncf-cla: yes, size/M

#512 kube-router-network-policy-pr-2018-8-22
  content/cn/docs/tasks/administer-cluster/network-policy-provider/kube-router-network-policy.md
Labels: cncf-cla: yes, size/M

#526 Translate docs/tasks/job/fine-parallel-processing-work-queue/index.md
  content/cn/docs/tasks/job/fine-parallel-processing-work-queue.md
Labels: cncf-cla: yes, size/L

#521 Translate docs/admin/salt.md
  content/cn/docs/setup/salt.md
Labels: cncf-cla: yes, size/L

#520 [WIP]Translate docs/admin/admission-controllers.md
  content/cn/docs/reference/access-authn-authz/admission-controllers.md
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/XL

#516 weave-network-policy-pr-2018-8-23
  content/cn/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy.md
Labels: cncf-cla: yes, size/M

#499 Update OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#539 fixed spelling error
  content/cn/docs/concepts/containers/images.md
  content/cn/docs/tasks/administer-cluster/cpu-memory-limit.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#541 Fix external link failed
  README-CN.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#532 Delete extra headlines
  content/cn/docs/tutorials/stateful-application/basic-stateful-set.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
